project:
  type: website
  output-dir: docs

website:
  title: "Izack Takazawa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: hobbies.qmd
        text: hobbies


format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

